// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.DAL
{
    using System.Linq;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;
    using System.Data.Common;
    using System.Runtime;
    using Oracle.ManagedDataAccess.Client;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class DAL : DALBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Oracle.ManagedDataAccess.Client;\r\nusing System;\r\nusing System.Collections.G" +
                    "eneric;\r\nusing System.Data;\r\nusing Core;\r\nusing Entity;\r\n\r\nnamespace DAL.DataAcc" +
                    "ess\r\n{\r\n    public class ");
            
            #line 35 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("DAL:DataAccessBase\r\n    {\r\n\r\n\t\t#region Constants\r\n\r\n        #region Procedure Nam" +
                    "es\r\n\r\n        protected const string DEL_");
            
            #line 42 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME = \"");
            
            #line 42 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_PKG.DEL_");
            
            #line 42 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_prc\";\r\n        protected const string GET_");
            
            #line 43 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME = \"");
            
            #line 43 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_PKG.GET_");
            
            #line 43 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_prc\";\r\n        protected const string ADD_");
            
            #line 44 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME = \"");
            
            #line 44 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_PKG.ADD_");
            
            #line 44 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_prc\";\r\n        protected const string UPD_");
            
            #line 45 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME = \"");
            
            #line 45 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_PKG.UPD_");
            
            #line 45 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_prc\";\r\n        protected const string SEARCH_");
            
            #line 46 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME = \"");
            
            #line 46 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_PKG.SEARCH_");
            
            #line 46 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("_prc\";\r\n\t\t#endregion\r\n\r\n        #region Parameter Names\r\n");
            
            #line 50 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
for(int i=0;i<columnTypeList.Count;i++){
            
            #line default
            #line hidden
            this.Write("        protected const string P_");
            
            #line 51 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i].ToUpper()));
            
            #line default
            #line hidden
            this.Write(" = \"P_");
            
            #line 51 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i].ToUpper()));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 52 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
}
            
            #line default
            #line hidden
            this.Write(@"		protected const string P_REFCURSOR_OUT = ""P_REFCURSOR_OUT"";
		protected const string P_ID_OUT = ""P_ID_OUT"";

		#region Pagination & Sorting
        protected const string P_CURRENT_PAGE = ""P_CURRENT_PAGE"";
        protected const string P_PAGE_SIZE = ""P_PAGE_SIZE"";
		protected const string P_TOTAL_RECORDS = ""P_TOTAL_RECORDS"";
		#endregion

		#endregion 

        #region Column Names

");
            
            #line 66 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
for(int i=0;i<columnTypeList.Count;i++){
            
            #line default
            #line hidden
            this.Write("        public const string ");
            
            #line 67 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i].ToUpper()));
            
            #line default
            #line hidden
            this.Write("_COLUMN_NAME = \"");
            
            #line 67 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i]));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 68 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t #endregion \r\n\t\t #endregion \r\n\r\n\t\t#region Methods\r\n        /// <summary>\r\n     " +
                    "   /// Search paged ");
            
            #line 74 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </summary>\r\n        /// <returns>return PagedSearchResult of ");
            
            #line 76 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("s.</returns>\r\n        /// <param name=\"currentPage\">Current page.</param>\r\n      " +
                    "  /// <param name=\"pageSize\">Page size.</param>\r\n        /// <param name=\"totalR" +
                    "ecord\">Total record.</param>\r\n        public PagedSearchResult<");
            
            #line 80 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> Search(int currentPage, int pageSize)\r\n        {\r\n\t\t\tList<");
            
            #line 82 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 82 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write("List = new List<");
            
            #line 82 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\tPagedSearchResult<");
            
            #line 83 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> result = new PagedSearchResult<");
            
            #line 83 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@">();
             OracleParameter[] Parameters =
              {
                new OracleParameter(P_CURRENT_PAGE,OracleDbType.Int32,currentPage,ParameterDirection.Input),
                new OracleParameter(P_PAGE_SIZE,OracleDbType.Int32,pageSize,ParameterDirection.Input),
                new OracleParameter(P_TOTAL_RECORDS,OracleDbType.Int32,0,ParameterDirection.Output),
                new OracleParameter(P_REFCURSOR_OUT,OracleDbType.RefCursor,null,ParameterDirection.Output),
            };
			OracleCommand oracleCommand = Connection.CreateCommand();
            oracleCommand.CommandType = CommandType.StoredProcedure;
            //Open DataReader
            using (OracleDataReader reader = DBHelper.ExecuteReader(Connection, oracleCommand, SEARCH_");
            
            #line 94 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME, Parameters))\r\n            {\r\n                while (reader.Read(" +
                    "))\r\n                {\r\n                    ");
            
            #line 98 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 98 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 98 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n                    GetEntityFromReader(reader, ");
            
            #line 99 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(");\r\n                    ");
            
            #line 100 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write("List.Add(");
            
            #line 100 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n            }\r\n\r\n            result.NumberOfRecords = Conv" +
                    "ert.ToInt32(DBHelper.GetParameterValue(oracleCommand,P_TOTAL_RECORDS));\r\n       " +
                    "     result.Collection = ");
            
            #line 105 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write("List;\r\n            return result;\r\n        }\r\n\r\n        /// <summary>\r\n        //" +
                    "/ Load ");
            
            #line 110 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" by Id.\r\n        /// </summary>\r\n        /// <returns>");
            
            #line 112 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" Object.</returns>\r\n        /// <param name=\"id\">Identifier.</param>\r\n        pub" +
                    "lic ");
            
            #line 114 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" Load(int id)\r\n        {\r\n\t\t\t");
            
            #line 116 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 116 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(@" = null;
			OracleParameter[] Parameters =
            {
                new OracleParameter(P_ID,OracleDbType.Int32,id,ParameterDirection.Input),
                new OracleParameter(P_REFCURSOR_OUT,OracleDbType.RefCursor,null,ParameterDirection.Output)
            };
			OracleCommand oracleCommand = new OracleCommand();
            oracleCommand.CommandType = CommandType.StoredProcedure;
            //Open DataReader
            using (OracleDataReader reader = DBHelper.ExecuteReader(Connection, oracleCommand, GET_");
            
            #line 125 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME, Parameters))\r\n            {\r\n                while (reader.Read(" +
                    "))\r\n                {\r\n                    if (");
            
            #line 129 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n                        ");
            
            #line 130 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 130 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n                    GetEntityFromReader(reader, ");
            
            #line 131 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n            }\r\n            return ");
            
            #line 134 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n        /// <summary>\r\n        /// Insert ");
            
            #line 138 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" to database.\r\n        /// </summary>\r\n        /// <returns>The inserted ");
            
            #line 140 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" Id.</returns>\r\n        /// <param name=\"");
            
            #line 141 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 141 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" object.</param>\r\n        public int Add(");
            
            #line 142 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 142 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {  \r\n\t\t\tOracleParameter[] Parameters =\r\n\t\t\t\t{\r\n\t");
            
            #line 146 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
for(int i=0;i<columnTypeList.Count;i++){
		if(columnNameList[i]!="ID" 
			&& columnNameList[i]!="DELETED_BY" 
			&& columnNameList[i]!="DELETION_DATE"
			&& columnNameList[i]!="MODIFIED_BY"
			&& columnNameList[i]!="MODIFICATION_DATE"
			&& columnNameList[i]!="CREATION_DATE"){
	
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tnew OracleParameter(P_");
            
            #line 154 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i].ToUpper()));
            
            #line default
            #line hidden
            this.Write(",OracleDbType.");
            
            #line 154 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDBType(columnTypeList[i])));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 154 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 154 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ToPascalCase(columnNameList[i])));
            
            #line default
            #line hidden
            this.Write(",ParameterDirection.Input),\r\n\t");
            
            #line 155 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
  }
	}
	
            
            #line default
            #line hidden
            this.Write(@"					new OracleParameter(P_ID_OUT,OracleDbType.Int32,null,ParameterDirection.Output)

          };
            OracleCommand oracleCommand = Connection.CreateCommand();
            oracleCommand.CommandType = CommandType.StoredProcedure;
            DBHelper.ExecuteNonQuery(Connection, oracleCommand, ADD_");
            
            #line 163 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME, Parameters);\r\n\r\n            ");
            
            #line 165 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(".Id = Convert.ToInt32(DBHelper.GetParameterValue(oracleCommand, P_ID_OUT));\r\n\r\n  " +
                    "          return ");
            
            #line 167 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(".Id;\r\n        }\r\n\r\n        /// <summary>\r\n        /// Update ");
            
            #line 171 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" into database.\r\n        /// </summary>\r\n        /// <param name=\"");
            
            #line 173 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 173 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" object.</param>\r\n        public void Update(");
            
            #line 174 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 174 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(")\r\n        { \r\n\t\t\tOracleParameter[] Parameters =\r\n            {\r\n\t\t\t\tnew OraclePa" +
                    "rameter(P_ID,OracleDbType.Int32,");
            
            #line 178 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(".Id,ParameterDirection.Input),\r\n           ");
            
            #line 179 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
for(int i=0;i<columnTypeList.Count;i++){
    if(columnNameList[i]!="ID" 
        && columnNameList[i]!="DELETED_BY" 
        && columnNameList[i]!="DELETION_DATE" 
        && columnNameList[i]!="MODIFICATION_DATE"
        && columnNameList[i]!="CREATION_DATE"
		&& columnNameList[i]!="CREATED_BY"){
            
            #line default
            #line hidden
            this.Write("                new OracleParameter(P_");
            
            #line 186 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i].ToUpper()));
            
            #line default
            #line hidden
            this.Write(",OracleDbType.");
            
            #line 186 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDBType(columnTypeList[i])));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 186 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 186 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ToPascalCase(columnNameList[i])));
            
            #line default
            #line hidden
            this.Write(",ParameterDirection.Input),\r\n\t ");
            
            #line 187 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
}}
            
            #line default
            #line hidden
            this.Write("};\r\n            OracleCommand oracleCommand = Connection.CreateCommand();\r\n      " +
                    "      oracleCommand.CommandType = CommandType.StoredProcedure;\r\n            DBHe" +
                    "lper.ExecuteNonQuery(Connection, oracleCommand, UPD_");
            
            #line 190 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME, Parameters);\r\n        }\r\n\r\n        /// <summary>\r\n        /// De" +
                    "lete ");
            
            #line 194 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@" by id from database(Soft Delete).
        /// </summary>
        /// <param name=""id"">Identifier.</param>
        public void Delete(int id,string deletedBy)
        {
             OracleParameter[] Parameters =
            {
                new OracleParameter(P_ID,OracleDbType.Int32,id,ParameterDirection.Input),
                new OracleParameter(P_DELETED_BY,OracleDbType.Varchar2,deletedBy,ParameterDirection.Input)
            };
            OracleCommand oracleCommand = Connection.CreateCommand();
            oracleCommand.CommandType = CommandType.StoredProcedure;
            DBHelper.ExecuteNonQuery(Connection, oracleCommand, DEL_");
            
            #line 206 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_PROCEDURE_NAME, Parameters);\r\n        }\r\n\r\n        /// <summary>\r\n        /// Fi" +
                    "ll ");
            
            #line 210 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" from reader\r\n        /// </summary>\r\n        /// <param name=\"ds\">reader object." +
                    "</param>\r\n\t\t/// <param name=\"ds\">");
            
            #line 213 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" object to be filled.</param>\r\n        public void GetEntityFromReader(OracleData" +
                    "Reader reader, ");
            
            #line 214 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        { \r\n\t\t\tint columnIndx = 0;\r\n");
            
            #line 217 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
for(int i=0;i<columnTypeList.Count;i++){
            
            #line default
            #line hidden
            this.Write("            if (ColumnExists(reader, ");
            
            #line 218 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i].ToUpper()));
            
            #line default
            #line hidden
            this.Write("_COLUMN_NAME))\r\n            {\r\n                columnIndx = reader.GetOrdinal(");
            
            #line 220 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnNameList[i].ToUpper()));
            
            #line default
            #line hidden
            this.Write("_COLUMN_NAME);\r\n                if (!reader.IsDBNull(columnIndx))\r\n              " +
                    "      entity.");
            
            #line 222 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ToPascalCase(columnNameList[i])));
            
            #line default
            #line hidden
            this.Write(" = Convert.");
            
            #line 222 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeCastType(columnTypeList[i],dataPrecision[i],dataScale[i])));
            
            #line default
            #line hidden
            this.Write("(reader[columnIndx]);\r\n            }\r\n");
            
            #line 224 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n\t\t#endregion\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 228 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"

public string GetDBType(string dbType)
{
    if(dbType=="NUMBER")
    {
        return "Int32";
    } else if(dbType=="VARCHAR2"){
        return "Varchar2";
    }else if(dbType=="CHAR"){
        return "Char";
    }else if(dbType=="BLOB"){
        return "Blob";
    }else if(dbType=="CLOB"){
        return "Clob";
    }else if(dbType=="DATE"){
        return "Date";
    }  else{
    return dbType;
    }
}

 public string GetType(string dbType,string dataPrecision,string dataScale)
{
    if(dbType=="NUMBER" && string.IsNullOrEmpty(dataPrecision)){
        return "int";
    }else if(dbType=="VARCHAR2"){
        return "string";
    }else if(dbType=="VARCHAR"){
        return "string";
    }else if(dbType=="CHAR"){
        return "string";
    }else if(dbType=="BLOB"){
        return "string";
    }else if(dbType=="CLOB"){
        return "string";
    }else if(dbType=="DATE"){
        return "DateTime";
    }else if(dbType=="NUMBER" && !string.IsNullOrEmpty(dataPrecision)  && int.Parse(dataPrecision)==1){
        return "bool";
    }else if(dbType=="NUMBER" && !string.IsNullOrEmpty(dataPrecision)  && int.Parse(dataPrecision)>1 
			&& !string.IsNullOrEmpty(dataScale) && int.Parse(dataPrecision)>0 ){
        return "double";
    }else{
    return dbType;
    }
}

public string GetTypeCastType(string dbType,string dataPrecision,string dataScale)
{
    if(dbType=="NUMBER" && string.IsNullOrEmpty(dataPrecision)){
        return "ToInt32";
    }else if(dbType=="VARCHAR2"){
        return "ToString";
    }else if(dbType=="VARCHAR"){
        return "ToString";
    }else if(dbType=="CHAR"){
        return "ToString";
    }else if(dbType=="BLOB"){
        return "ToString";
    }else if(dbType=="CLOB"){
        return "ToString";
    }else if(dbType=="DATE"){
        return "ToDateTime";
    }else if(dbType=="NUMBER" && !string.IsNullOrEmpty(dataPrecision)  && int.Parse(dataPrecision)==1){
        return "ToBoolean";
    }else if(dbType=="NUMBER" && !string.IsNullOrEmpty(dataPrecision)  && int.Parse(dataPrecision)>1 
			&& !string.IsNullOrEmpty(dataScale) && int.Parse(dataPrecision)>0 ){
        return "ToDouble";
    }else{
    return dbType;
    }
}

public string GetNullableType(string dbType,string dataPrecision,string dataScale)
{
    if(dbType=="NUMBER" && string.IsNullOrEmpty(dataPrecision)){
        return "int?";
    }else if(dbType=="VARCHAR2"){
        return "string";
    }else if(dbType=="VARCHAR"){
        return "string";
    }else if(dbType=="BLOB"){
        return "string";
    }else if(dbType=="CLOB"){
        return "string";
    }else if(dbType=="DATE"){
        return "DateTime?";
    }else if(dbType=="NUMBER" && !string.IsNullOrEmpty(dataPrecision)  && dataPrecision=="1"){
        return "bool?";
    }else if(dbType=="NUMBER" && !string.IsNullOrEmpty(dataPrecision)  && int.Parse(dataPrecision)>1 
			&& !string.IsNullOrEmpty(dataScale) && int.Parse(dataPrecision)>0 ){
        return "double?";
    }else{
    return dbType;
    }
}

public static string GetClassName(string text)
{
    text = ToPascalCase(text);
    if(text.IndexOf('s')==text.Length-1){
        string result = text.Remove(text.LastIndexOf('s'));
        return result;
    }
    return text;
}

public static string ToPascalCase(string text)
{
    string result = text.Split('_').Select(s => char.ToUpperInvariant(s[0]) + s.Substring(1, s.Length - 1).ToLower()).Aggregate(string.Empty, (s1, s2) => s1 + s2); ;
    return result;
}

public static string GetObjectName(string text)
{
    text = ToPascalCase(text);
    text = Char.ToLower(text[0]) + text.Substring(1, text.Length - 1);
    if (text.LastIndexOf('s') == text.Length - 1)
    {
        text = text.Remove(text.LastIndexOf('s'));
    }
    return text;
}

        
        #line default
        #line hidden
        
        #line 1 "C:\Workspaces\Generator\Generator\DAL\DAL.tt"

private string _tableNameField;

/// <summary>
/// Access the tableName parameter of the template.
/// </summary>
private string tableName
{
    get
    {
        return this._tableNameField;
    }
}

private global::System.Collections.Generic.List<string> _columnNameListField;

/// <summary>
/// Access the columnNameList parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<string> columnNameList
{
    get
    {
        return this._columnNameListField;
    }
}

private global::System.Collections.Generic.List<string> _columnTypeListField;

/// <summary>
/// Access the columnTypeList parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<string> columnTypeList
{
    get
    {
        return this._columnTypeListField;
    }
}

private global::System.Collections.Generic.List<string> _nullableListField;

/// <summary>
/// Access the nullableList parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<string> nullableList
{
    get
    {
        return this._nullableListField;
    }
}

private global::System.Collections.Generic.List<string> _dataPrecisionField;

/// <summary>
/// Access the dataPrecision parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<string> dataPrecision
{
    get
    {
        return this._dataPrecisionField;
    }
}

private global::System.Collections.Generic.List<string> _dataScaleField;

/// <summary>
/// Access the dataScale parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<string> dataScale
{
    get
    {
        return this._dataScaleField;
    }
}

private string _ClassNameField;

/// <summary>
/// Access the ClassName parameter of the template.
/// </summary>
private string ClassName
{
    get
    {
        return this._ClassNameField;
    }
}

private string _ObjectNameField;

/// <summary>
/// Access the ObjectName parameter of the template.
/// </summary>
private string ObjectName
{
    get
    {
        return this._ObjectNameField;
    }
}

private string _AngularFileNameField;

/// <summary>
/// Access the AngularFileName parameter of the template.
/// </summary>
private string AngularFileName
{
    get
    {
        return this._AngularFileNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool tableNameValueAcquired = false;
if (this.Session.ContainsKey("tableName"))
{
    this._tableNameField = ((string)(this.Session["tableName"]));
    tableNameValueAcquired = true;
}
if ((tableNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("tableName");
    if ((data != null))
    {
        this._tableNameField = ((string)(data));
    }
}
bool columnNameListValueAcquired = false;
if (this.Session.ContainsKey("columnNameList"))
{
    this._columnNameListField = ((global::System.Collections.Generic.List<string>)(this.Session["columnNameList"]));
    columnNameListValueAcquired = true;
}
if ((columnNameListValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("columnNameList");
    if ((data != null))
    {
        this._columnNameListField = ((global::System.Collections.Generic.List<string>)(data));
    }
}
bool columnTypeListValueAcquired = false;
if (this.Session.ContainsKey("columnTypeList"))
{
    this._columnTypeListField = ((global::System.Collections.Generic.List<string>)(this.Session["columnTypeList"]));
    columnTypeListValueAcquired = true;
}
if ((columnTypeListValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("columnTypeList");
    if ((data != null))
    {
        this._columnTypeListField = ((global::System.Collections.Generic.List<string>)(data));
    }
}
bool nullableListValueAcquired = false;
if (this.Session.ContainsKey("nullableList"))
{
    this._nullableListField = ((global::System.Collections.Generic.List<string>)(this.Session["nullableList"]));
    nullableListValueAcquired = true;
}
if ((nullableListValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("nullableList");
    if ((data != null))
    {
        this._nullableListField = ((global::System.Collections.Generic.List<string>)(data));
    }
}
bool dataPrecisionValueAcquired = false;
if (this.Session.ContainsKey("dataPrecision"))
{
    this._dataPrecisionField = ((global::System.Collections.Generic.List<string>)(this.Session["dataPrecision"]));
    dataPrecisionValueAcquired = true;
}
if ((dataPrecisionValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("dataPrecision");
    if ((data != null))
    {
        this._dataPrecisionField = ((global::System.Collections.Generic.List<string>)(data));
    }
}
bool dataScaleValueAcquired = false;
if (this.Session.ContainsKey("dataScale"))
{
    this._dataScaleField = ((global::System.Collections.Generic.List<string>)(this.Session["dataScale"]));
    dataScaleValueAcquired = true;
}
if ((dataScaleValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("dataScale");
    if ((data != null))
    {
        this._dataScaleField = ((global::System.Collections.Generic.List<string>)(data));
    }
}
bool ClassNameValueAcquired = false;
if (this.Session.ContainsKey("ClassName"))
{
    this._ClassNameField = ((string)(this.Session["ClassName"]));
    ClassNameValueAcquired = true;
}
if ((ClassNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ClassName");
    if ((data != null))
    {
        this._ClassNameField = ((string)(data));
    }
}
bool ObjectNameValueAcquired = false;
if (this.Session.ContainsKey("ObjectName"))
{
    this._ObjectNameField = ((string)(this.Session["ObjectName"]));
    ObjectNameValueAcquired = true;
}
if ((ObjectNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ObjectName");
    if ((data != null))
    {
        this._ObjectNameField = ((string)(data));
    }
}
bool AngularFileNameValueAcquired = false;
if (this.Session.ContainsKey("AngularFileName"))
{
    this._AngularFileNameField = ((string)(this.Session["AngularFileName"]));
    AngularFileNameValueAcquired = true;
}
if ((AngularFileNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AngularFileName");
    if ((data != null))
    {
        this._AngularFileNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class DALBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
